// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy-_kfYPtA3P8o349BuJpo7lTCYZSu084',
    appId: '1:895541567814:web:69936aa51a3ef8478cc547',
    messagingSenderId: '895541567814',
    projectId: 'upstage-global-ai-week-2024',
    authDomain: 'upstage-global-ai-week-2024.firebaseapp.com',
    storageBucket: 'upstage-global-ai-week-2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqfzGagVZDjMmYWY9IAoxEk8awWNQIZxE',
    appId: '1:895541567814:android:cac62bd5bf274ecd8cc547',
    messagingSenderId: '895541567814',
    projectId: 'upstage-global-ai-week-2024',
    storageBucket: 'upstage-global-ai-week-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSniMWur_Ojve_sJR1J1mp7ZNElP6yqFw',
    appId: '1:895541567814:ios:7b29c514cbd99a0a8cc547',
    messagingSenderId: '895541567814',
    projectId: 'upstage-global-ai-week-2024',
    storageBucket: 'upstage-global-ai-week-2024.appspot.com',
    iosBundleId: 'com.example.juju',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSniMWur_Ojve_sJR1J1mp7ZNElP6yqFw',
    appId: '1:895541567814:ios:7b29c514cbd99a0a8cc547',
    messagingSenderId: '895541567814',
    projectId: 'upstage-global-ai-week-2024',
    storageBucket: 'upstage-global-ai-week-2024.appspot.com',
    iosBundleId: 'com.example.juju',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy-_kfYPtA3P8o349BuJpo7lTCYZSu084',
    appId: '1:895541567814:web:67ce08229b33b6ae8cc547',
    messagingSenderId: '895541567814',
    projectId: 'upstage-global-ai-week-2024',
    authDomain: 'upstage-global-ai-week-2024.firebaseapp.com',
    storageBucket: 'upstage-global-ai-week-2024.appspot.com',
  );

}