// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXPUg3k6Sn4ouCbg1W3DCc5T0sklL_xaw',
    appId: '1:973831618728:web:bb41b60cd0a25b89a8c29d',
    messagingSenderId: '973831618728',
    projectId: 'llama-hackathon-2024',
    authDomain: 'llama-hackathon-2024.firebaseapp.com',
    storageBucket: 'llama-hackathon-2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ9gtNpXsLwn7SphdMt9aj40GAABoRRaE',
    appId: '1:973831618728:android:96c66070bfd4cbd8a8c29d',
    messagingSenderId: '973831618728',
    projectId: 'llama-hackathon-2024',
    storageBucket: 'llama-hackathon-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALmlrGBU1jrURXsKCkk9LVcafoGBJW4Ug',
    appId: '1:973831618728:ios:c38008fd5f0af7c1a8c29d',
    messagingSenderId: '973831618728',
    projectId: 'llama-hackathon-2024',
    storageBucket: 'llama-hackathon-2024.appspot.com',
    iosBundleId: 'com.example.stour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALmlrGBU1jrURXsKCkk9LVcafoGBJW4Ug',
    appId: '1:973831618728:ios:c38008fd5f0af7c1a8c29d',
    messagingSenderId: '973831618728',
    projectId: 'llama-hackathon-2024',
    storageBucket: 'llama-hackathon-2024.appspot.com',
    iosBundleId: 'com.example.stour',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXPUg3k6Sn4ouCbg1W3DCc5T0sklL_xaw',
    appId: '1:973831618728:web:7f058405a9b47a9ba8c29d',
    messagingSenderId: '973831618728',
    projectId: 'llama-hackathon-2024',
    authDomain: 'llama-hackathon-2024.firebaseapp.com',
    storageBucket: 'llama-hackathon-2024.appspot.com',
  );
}
